# Generated by Django 5.1.4 on 2024-12-13 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('res', models.IntegerField(default=0)),
                ('fecha', models.DateField(default='2024-01-01')),
                ('lcl', models.CharField(default='Desconocido', max_length=200)),
                ('total', models.IntegerField()),
                ('documento', models.FileField(upload_to='convenios/')),
            ],
            options={
                'db_table': 'Convenios',
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Municipios')),
                ('rut', models.CharField(max_length=20, verbose_name='Rut')),
                ('cuenta', models.CharField(max_length=50, verbose_name='Cuenta')),
            ],
            options={
                'db_table': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='programas/')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialConvenios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('res', models.IntegerField(default=0)),
                ('lcl', models.CharField(default='Desconocido', max_length=200)),
                ('total', models.IntegerField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='historial_convenios/')),
                ('convenio_madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='Sistema1.convenios')),
            ],
            options={
                'db_table': 'HistorialConvenios',
                'ordering': ['-fecha_modificacion'],
            },
        ),
        migrations.AddField(
            model_name='convenios',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convenios', to='Sistema1.municipios'),
        ),
        migrations.AddField(
            model_name='municipios',
            name='programas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='Sistema1.programas'),
        ),
        migrations.CreateModel(
            name='Rendiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_rendicion', models.CharField(choices=[('enero', 'Enero'), ('febrero', 'Febrero'), ('marzo', 'Marzo'), ('abril', 'abril'), ('mayo', 'Mayo'), ('junio', 'Junio'), ('julio', 'Julio'), ('agosto', 'Agosto'), ('septiembre', 'Septiembre'), ('octubre', 'Octubre'), ('noviembre', 'Noviembre'), ('diciembre', 'Diciembre')], default='enero', max_length=200)),
                ('numero_oficio', models.IntegerField()),
                ('estado', models.CharField(choices=[('rendido', 'Rendido'), ('sin_rendir', 'Sin Rendir'), ('cancelado', 'Cancelado')], default='sin_rendir', max_length=10)),
                ('fecha_de_oficio', models.DateField(max_length=200)),
                ('n_nemo_interno', models.IntegerField()),
                ('n_sigfe', models.IntegerField()),
                ('fecha_sigfe', models.DateField(max_length=200)),
                ('fecha_actual', models.DateField(max_length=200)),
                ('gasto_operacional', models.IntegerField()),
                ('gasto_personal', models.IntegerField()),
                ('gasto_inversion', models.IntegerField()),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sistema1.convenios')),
            ],
            options={
                'db_table': 'Rendiciones',
            },
        ),
    ]
