# Generated by Django 5.1.4 on 2024-12-13 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialconvenios',
            name='fecha',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
    ]
