# Generated by Django 4.2.3 on 2024-12-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema1', '0004_municipios_banco_alter_convenios_fecha'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='programas',
            table='Programas',
        ),
    ]
