# Generated by Django 4.2.3 on 2024-12-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema1', '0005_alter_programas_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipios',
            name='tcuenta',
            field=models.CharField(choices=[('Cuenta_Corriente', 'Cuenta Corriente'), ('Cuenta_vista', 'Cuenta vista'), ('Cuenta_Rut', 'Cuenta Rut'), ('Cuenta_Ahorro', 'Cuenta Ahorro'), ('Otro', 'Otro')], default='Cuenta_Corriente', max_length=200),
        ),
    ]
