# Generated by Django 4.2.3 on 2024-12-16 05:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema1', '0006_municipios_tcuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reintegros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(help_text='Fecha en que se solicitó el reintegro.')),
                ('fecha_aprobacion', models.DateField(help_text='Fecha en que se aprobó el reintegro.')),
                ('codigo_referencia', models.CharField(help_text='Código único de referencia del reintegro.', max_length=255)),
                ('numero_oficio', models.PositiveIntegerField(help_text='Número de oficio relacionado.', validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_oficio', models.DateField(help_text='Fecha del oficio.')),
                ('numero_sigfe', models.PositiveIntegerField(help_text='Número asociado en SIGFE.', validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_sigfe', models.DateField(help_text='Fecha asociada en SIGFE.')),
                ('monto_entregado', models.PositiveIntegerField(help_text='Monto entregado inicialmente.', validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_reintegrar', models.PositiveIntegerField(help_text='Monto que debe reintegrarse.', validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o detalle del reintegro.', max_length=5000)),
                ('fecha_creacion', models.DateField(auto_now_add=True, help_text='Fecha en que se creó el registro.')),
                ('fecha_limite_devolucion', models.DateField(help_text='Fecha límite para la devolución del monto.')),
                ('estado_reintegro', models.CharField(choices=[('reintegrado', 'Reintegrado'), ('sin_reintegrar', 'Sin Reintegrar'), ('cancelado', 'Cancelado')], default='sin_reintegrar', help_text='Estado actual del reintegro.', max_length=20)),
                ('documento', models.FileField(blank=True, help_text='Documento adjunto relacionado con el reintegro.', null=True, upload_to='reintegros/')),
                ('convenio', models.ForeignKey(blank=True, help_text='Convenio relacionado con el reintegro.', null=True, on_delete=django.db.models.deletion.CASCADE, to='Sistema1.convenios')),
            ],
            options={
                'db_table': 'Reintegros',
            },
        ),
    ]
