# Generated by Django 4.2.3 on 2024-12-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema1', '0007_reintegros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reintegros',
            name='monto_entregado',
            field=models.IntegerField(help_text='Monto entregado inicialmente.'),
        ),
        migrations.AlterField(
            model_name='reintegros',
            name='monto_reintegrar',
            field=models.IntegerField(help_text='Monto que debe reintegrarse.'),
        ),
        migrations.AlterField(
            model_name='reintegros',
            name='numero_oficio',
            field=models.IntegerField(help_text='Número de oficio relacionado.'),
        ),
        migrations.AlterField(
            model_name='reintegros',
            name='numero_sigfe',
            field=models.IntegerField(help_text='Número asociado en SIGFE.'),
        ),
    ]
