# Generated by Django 4.2.3 on 2024-12-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema1', '0008_alter_reintegros_monto_entregado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendiciones',
            name='descripcion',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
